# Development config

spring:
  data:
    mongodb:
      uri: mongodb+srv://jumpstart:jumpstart@cluster0.xfvbu51.mongodb.net/hrs
      auto-index-creation: true
      uuid-representation: standard
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api
