# Development config

spring:
  data:
    mongodb:
      uri: mongodb+srv://jumpstart:jumpstart@cluster0.xfvbu51.mongodb.net/hrs # mongodb://localhost:27017/hrs
      auto-index-creation: true
      uuid-representation: standard
