spring:
  application:
    name: hrs

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    mongodb:
      auto-index-creation: true
      uuid-representation: standard

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liZ1tPryYifyyYhY
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
          google:
            client-id: 249191790614-1dofquvhuita6ahs897a5qdocj7kpnd5.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}

server:
  forward-headers-strategy: native
  port: ${SERVER_PORT:5000}
  address: 0.0.0.0
  servlet:
    context-path: /api

app:
  email:
    from: stormstay@proton.me

  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:3000}

stripe:
  api:
    key: ${STRIPE_TEST_KEY}
  webhook:
    secret:
