name: Automatic Build & Deploy (CI/CD)

on:
  push:
    branches:
      - main

jobs:
  
  build backend & frontend:
    name: Build Backend & Frontend
    uses: ./.github/workflows/build.yml
    id: build_job
    with:
      branch_name: main

  deploy-backend:
    needs: build backend & frontend
    uses: ./.github/workflows/deploy-backend.yml
    with:
      build_run_id: ${{ needs.build backend & frontend.outputs.build_run_id }}
      deploy_to_eb: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-frontend:
    needs: deploy-backend
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      build_run_id: ${{ needs.build backend & frontend.outputs.build_run_id }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}