name: Build Backend & Frontend

on:

  push:
    branches:
      - develop
      
  pull_request:
    branches:
      - develop
      
  workflow_dispatch:
     inputs:
      branch_name:
        description: 'The name of the branch to build'
        required: true
        default: 'develop'
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      STRIPE_TEST_KEY: ${{ secrets.STRIPE_TEST_KEY }}
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      VITE_HOME_VIDEO_URL: ${{ vars.VITE_HOME_VIDEO_URL }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: List root directory
        run: ls -R /home/runner/work/hrs/hrs/
        
      ############################
      # Frontend
      ############################
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install frontend dependencies
        working-directory: /home/runner/work/hrs/hrs/frontend
        run: npm ci

      - name: Build frontend
        working-directory: /home/runner/work/hrs/hrs/frontend
        run: npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: /home/runner/work/hrs/hrs/frontend/dist
          retention-days: 7

      ############################
      # Backend
      ############################
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        working-directory: /home/runner/work/hrs/hrs/backend
        run: chmod +x mvnw

      - name: Build backend
        working-directory: /home/runner/work/hrs/hrs/backend
        run: ./mvnw clean package

      - name: Rename jar to fixed name
        working-directory: /home/runner/work/hrs/hrs/backend/target
        run: |
          ls
          cp hrs-0.0.1-SNAPSHOT.jar hrs-backend.jar

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-target
          path: /home/runner/work/hrs/hrs/backend/target/hrs-backend.jar
          retention-days: 7
