name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: "Build workflow run ID"
        required: true
        type: string
      deploy_to_eb:
        description: "Deploy instance? (create application version only if false)"
        required: false
        type: boolean
        default: false

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      build_run_id: ${{ inputs.build_run_id }}
      deploy_to_eb: ${{ inputs.deploy_to_eb }}

  deploy-frontend:
    needs: deploy-backend
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      build_run_id: ${{ inputs.build_run_id }}