name: Manual Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch to build
        required: true
        default: main
        type: string

      deploy_to_eb:
        description: "Deploy instance? (create application version only if false)"
        required: false
        type: boolean
        default: false

jobs:
  
  build:
    name: Build Frontend & Backend
    uses: ./.github/workflows/build.yml
    with:
      branch_name: ${{ inputs.branch_name }}

  deploy-backend:
    needs: build
    uses: ./.github/workflows/deploy-backend.yml
    with:
      build_run_id: ${{ needs.build.outputs.build_run_id }}
      deploy_to_eb: ${{ inputs.deploy_to_eb }}

  deploy-frontend:
    needs: [build, deploy-backend]
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      build_run_id: ${{ needs.build.outputs.build_run_id }}