name: Manual Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch to build
        required: true
        default: main
        type: string

      deploy_to_eb:
        description: "Deploy instance? (create application version only if false)"
        required: false
        type: boolean
        default: false

jobs:
  
  build frontend & backend:
    name: Build Frontend & Backend
    uses: ./.github/workflows/build.yml
    id: build_job
    with:
      branch_name: ${{ inputs.branch_name }}

  deploy-backend:
    needs: build frontend & backend
    uses: ./.github/workflows/deploy-backend.yml
    with:
      build_run_id: ${{ needs.build frontend & backend.outputs.build_run_id }}
      deploy_to_eb: ${{ github.event.inputs.deploy_to_eb }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-frontend:
    needs: deploy-backend
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      build_run_id: ${{ needs.build frontend & backend.outputs.build_run_id }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}