name: Manual Build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch to build
        required: true
        default: main
        type: string
jobs:
  build:
    name: Build Frontend & Backend
    uses: ./.github/workflows/build.yml
    with:
      branch_name: ${{ inputs.branch_name }}
