name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: "Build workflow run ID"
        required: true
        type: string
      deploy_to_eb:
        description: "Deploy instance? (create application version only if false)"
        required: false
        type: boolean
        default: false

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      build_run_id: ${{ github.event.inputs.build_run_id }}
      deploy_to_eb: ${{ github.event.inputs.deploy_to_eb }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-frontend:
    needs: deploy-backend
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      build_run_id: ${{ github.event.inputs.build_run_id }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}