name: Build Backend & Frontend

on:
  push:
    branches:
      - feature/workflow

  workflow_dispatch:
     inputs:
      branch_name:
        description: 'The name of the branch to build'
        required: true
        default: 'feature/workflow'
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      STRIPE_TEST_KEY: ${{ secrets.STRIPE_TEST_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}

      ############################
      # Frontend
      ############################
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: hrs/frontend/package-lock.json
      
      - name: Install frontend dependencies
        working-directory: hrs/frontend
        run: npm ci

      - name: Build frontend
        working-directory: hrs/frontend
        run: npm run build

      ############################
      # Backend
      ############################
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        working-directory: hrs/backend
        run: chmod +x mvnw

      - name: Build backend
        working-directory: hrs/backend
        run: ./mvnw clean package
